packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog: 
  eslint: "^9.15.0"
  prettier: ^3.3.3
  zod: ^3.24.1
  "@t3-oss/env-nextjs": ^0.11.1
  typescript: ^5.3.3
  tailwindcss: ^3.4.14



catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19

  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  
  nextjs15:
    next: 15.1.3
  nextjs15-canary:
    next: 15.1.1-canary.25
